### ISSUE TITLE
Django collect static error

### ISSUE THREAD

**Issue by suecharo** [suecharo/SAPPORO#22]
```
sapporo-web-app | Type 'yes' to continue, or 'no' to cancel: Traceback (most recent call last):
sapporo-web-app |   File "/opt/SAPPORO-web/SAPPORO-web/manage.py", line 23, in <module>
sapporo-web-app |     execute_from_command_line(sys.argv)
sapporo-web-app |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
sapporo-web-app |     utility.execute()
sapporo-web-app |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
sapporo-web-app |     self.fetch_command(subcommand).run_from_argv(self.argv)
sapporo-web-app |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
sapporo-web-app |     self.execute(*args, **cmd_options)
sapporo-web-app |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
sapporo-web-app |     output = self.handle(*args, **options)
sapporo-web-app |   File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 185, in handle
sapporo-web-app |     if input(''.join(message)) != 'yes':
sapporo-web-app | EOFError: EOF when reading a line
```

**Comment by suecharo** [comment]
https://stackoverflow.com/questions/8705305/automated-django-receive-hook-on-server-respond-to-collectstatic-with-yes

**Comment by chetabahana** [comment]
It might need to append the --noinput argument:

`
python manage.py collectstatic  --noinput
`

See explanation: [DJANGO - Not able to run collectstatic](http://howtoinstallthisapp.blogspot.com/2018/01/django-not-able-to-run-collectstatic-on.html)

**Comment by suecharo** [comment]
Thank you for the advice.
